version: '3.9'
services:
  backend:
    container_name: kupi-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: kupi-backend
    ports:
      - 4000:3000
    env_file:
      - .env
  frontend:
    container_name: kupi-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: kupi-frontend
    ports:
      - 4001:3000
  postgres:
    container_name: kupi-postgres
    image: postgres
    env_file:
      - .env
  adminer:
    container_name: kupi-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
